package hr.unipu

import javafx.application.Application
import javafx.event.EventHandler
import javafx.geometry.Pos
import javafx.scene.Scene
import javafx.scene.control.Button
import javafx.scene.control.Label
import javafx.scene.layout.BorderPane
import javafx.scene.layout.VBox
import javafx.stage.Stage

/**
 * Plant Computer Controller JavaFX class.
 */
class PlantComputerControllerApplication : Application() {

    /**
     * start() method with primary stage autogenerated.
     * @param primaryStage JavaFX auto-generated primary stage.
     */
    override fun start(primaryStage: Stage) {

        // Title, Root, Scene.
        primaryStage.title = "Hello JavaFX"
        val root = BorderPane()
        val scene = Scene(root, 300.0, 250.0) // Common dimensions: 640x800, 300x250.

        // Label.
        val javaVersion = System.getProperty("java.version")
        val javafxVersion = System.getProperty("javafx.version")
        val text = "KOTLIN: Hello, JavaFX $javafxVersion, running on Java $javaVersion."
        val lbl = Label()

        // Button.
        val btn = Button()
        btn.text = "KOTLIN: Hello GPIO JavaFX"
        btn.onAction = EventHandler {
            // Terminal print.
            println(text)
            // Window print.
            lbl.text = text
        }

        // Add(all) nodes to root.
        val vBox = VBox()
        vBox.alignment = Pos.CENTER
        vBox.children.addAll(btn, lbl)

        root.center = vBox

        primaryStage.scene = scene
        primaryStage.show()
    }


    companion object {
        /**
         * JavaFX app entry point.
         * @param args Command line arguments.
         */
        @JvmStatic fun main(args: Array<String>) {
            //launch(*args)
            launch(PlantComputerControllerApplication::class.java, *args)
        }
    }


}